name: MarshallCore
version: ${project.version}
main: me.marshall.MarshallCore.Core
api-version: 1.13
authors: [Marshall]
description: Menu Manager
website: https://www.github.com/marshallr7
commands:
  examplecommand:
    description:
